#!/bin/bash
#
# Configure U-Boot for BananaPro 5-inch LCD Display
# Based on sunxi-linux LCD configuration table
#

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
UBOOT_DIR="${PROJECT_DIR}/repos/u-boot"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# LCD Configuration for 5-inch display
LCD_CONFIG=(
    "CONFIG_VIDEO_SUNXI=y"
    'CONFIG_VIDEO_LCD_MODE="x:800,y:480,depth:24,pclk_khz:30000,le:40,ri:40,up:29,lo:13,hs:48,vs:3,sync:3,vmode:0"'
    'CONFIG_VIDEO_LCD_POWER="PH12"'
    'CONFIG_VIDEO_LCD_BL_EN="PH8"'
    'CONFIG_VIDEO_LCD_BL_PWM="PB2"'
    "CONFIG_VIDEO_LCD_BL_PWM_ACTIVE_LOW=n"
    "CONFIG_CONSOLE_MUX=y"
    "CONFIG_VIDEO=y"
    "CONFIG_DM_VIDEO=y"
    "CONFIG_DISPLAY=y"
)

echo -e "${GREEN}=== BananaPro 5-inch LCD Configuration Script ===${NC}"
echo ""

# Check if U-Boot directory exists
if [ ! -d "$UBOOT_DIR" ]; then
    echo -e "${RED}Error: U-Boot directory not found at $UBOOT_DIR${NC}"
    exit 1
fi

echo -e "${YELLOW}U-Boot directory: $UBOOT_DIR${NC}"
echo ""

# Function to update U-Boot defconfig
update_defconfig() {
    local defconfig_file="$1"
    
    if [ ! -f "$defconfig_file" ]; then
        echo -e "${RED}Error: Defconfig file not found: $defconfig_file${NC}"
        return 1
    fi
    
    echo -e "${GREEN}Updating defconfig: $(basename "$defconfig_file")${NC}"
    
    # Create backup
    cp "$defconfig_file" "${defconfig_file}.backup"
    echo -e "${YELLOW}Backup created: ${defconfig_file}.backup${NC}"
    
    # Add or update LCD configuration
    for config_line in "${LCD_CONFIG[@]}"; do
        config_name=$(echo "$config_line" | cut -d'=' -f1)
        
        # Remove existing configuration if present
        sed -i "/^${config_name}=/d" "$defconfig_file"
        sed -i "/^# ${config_name} is not set/d" "$defconfig_file"
        
        # Add new configuration
        echo "$config_line" >> "$defconfig_file"
        echo "  Added: $config_line"
    done
    
    echo -e "${GREEN}Defconfig updated successfully!${NC}"
    echo ""
}

# Function to create a custom defconfig fragment
create_config_fragment() {
    local fragment_file="${UBOOT_DIR}/configs/lcd_5inch.fragment"
    
    echo -e "${GREEN}Creating configuration fragment: $fragment_file${NC}"
    
    cat > "$fragment_file" << 'EOF'
# 5-inch LCD Configuration Fragment for BananaPro
# Resolution: 800x480, 24-bit color depth
# Generated by configure_5inch_lcd.sh

# Enable video support
CONFIG_VIDEO_SUNXI=y
CONFIG_VIDEO=y
CONFIG_DM_VIDEO=y
CONFIG_DISPLAY=y
CONFIG_CONSOLE_MUX=y

# LCD timing configuration
CONFIG_VIDEO_LCD_MODE="x:800,y:480,depth:24,pclk_khz:30000,le:40,ri:40,up:29,lo:13,hs:48,vs:3,sync:3,vmode:0"

# GPIO configuration
CONFIG_VIDEO_LCD_POWER="PH12"
CONFIG_VIDEO_LCD_BL_EN="PH8"
CONFIG_VIDEO_LCD_BL_PWM="PB2"
CONFIG_VIDEO_LCD_BL_PWM_ACTIVE_LOW=n
EOF
    
    echo -e "${GREEN}Fragment created: $fragment_file${NC}"
    echo ""
}

# Function to display current LCD configuration
show_current_config() {
    local defconfig_file="$1"
    
    if [ ! -f "$defconfig_file" ]; then
        echo -e "${RED}Error: Defconfig file not found${NC}"
        return 1
    fi
    
    echo -e "${GREEN}Current LCD-related configuration:${NC}"
    echo "-----------------------------------"
    grep -E "CONFIG_VIDEO|CONFIG_LCD|CONFIG_DISPLAY" "$defconfig_file" || echo "No LCD configuration found"
    echo "-----------------------------------"
    echo ""
}

# Main menu
echo "Select an option:"
echo "1) Update existing defconfig (BananaPi M1 Plus)"
echo "2) Create configuration fragment only"
echo "3) Show current configuration"
echo "4) Display LCD configuration details"
echo "5) Exit"
echo ""
read -p "Enter your choice [1-5]: " choice

case $choice in
    1)
        # List available defconfigs
        echo ""
        echo "Available defconfigs in U-Boot:"
        find "$UBOOT_DIR/configs" -name "*banan*" -o -name "*sun7i*" | sort
        echo ""
        
        read -p "Enter defconfig filename (e.g., bananapi_m1_plus_defconfig): " defconfig_name
        
        if [ -z "$defconfig_name" ]; then
            defconfig_name="bananapi_m1_plus_defconfig"
        fi
        
        defconfig_path="${UBOOT_DIR}/configs/${defconfig_name}"
        
        if [ -f "$defconfig_path" ]; then
            update_defconfig "$defconfig_path"
            echo -e "${GREEN}Next steps:${NC}"
            echo "1. cd $UBOOT_DIR"
            echo "2. make ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- ${defconfig_name}"
            echo "3. make ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- -j\$(nproc)"
        else
            echo -e "${RED}Error: Defconfig not found: $defconfig_path${NC}"
            exit 1
        fi
        ;;
    2)
        create_config_fragment
        echo -e "${GREEN}To use this fragment:${NC}"
        echo "scripts/kconfig/merge_config.sh -m configs/your_defconfig configs/lcd_5inch.fragment"
        ;;
    3)
        read -p "Enter defconfig filename (e.g., bananapi_m1_plus_defconfig): " defconfig_name
        if [ -z "$defconfig_name" ]; then
            defconfig_name="bananapi_m1_plus_defconfig"
        fi
        defconfig_path="${UBOOT_DIR}/configs/${defconfig_name}"
        show_current_config "$defconfig_path"
        ;;
    4)
        echo ""
        echo -e "${GREEN}=== 5-inch LCD Configuration Details ===${NC}"
        echo ""
        echo "Resolution:      800x480 pixels"
        echo "Color Depth:     24-bit (RGB888)"
        echo "Pixel Clock:     30 MHz"
        echo ""
        echo "Horizontal Timings:"
        echo "  Active:        800 pixels"
        echo "  Front Porch:   40 pixels  (ri)"
        echo "  Sync Width:    48 pixels  (hs)"
        echo "  Back Porch:    40 pixels  (le)"
        echo "  Total:         928 pixels"
        echo ""
        echo "Vertical Timings:"
        echo "  Active:        480 lines"
        echo "  Front Porch:   13 lines   (lo)"
        echo "  Sync Width:    3 lines    (vs)"
        echo "  Back Porch:    29 lines   (up)"
        echo "  Total:         525 lines"
        echo ""
        echo "GPIO Pins:"
        echo "  Power:         PH12"
        echo "  Backlight EN:  PH8"
        echo "  Backlight PWM: PB2"
        echo ""
        echo "Refresh Rate: ~60 Hz"
        echo "  Formula: (30000 * 1000) / (928 * 525) ≈ 61.6 Hz"
        echo ""
        ;;
    5)
        echo "Exiting..."
        exit 0
        ;;
    *)
        echo -e "${RED}Invalid choice${NC}"
        exit 1
        ;;
esac

echo ""
echo -e "${GREEN}Done!${NC}"
echo ""
echo "For more details, see: docs/LCD_5INCH_CONFIGURATION.md"
